# Ans 1

In [2]:
import numpy as np

In [2]:
arr= np.arange(2,51,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

# Ans 2

In [29]:
l1=[]
l2=[]
for i in range(5):
    l1.append(int(input()))
for i in range(5):
    l2.append(int(input()))
arr1=np.array(l1)
arr2=np.array(l2)
newarr=np.concatenate((arr1,arr2))
np.sort(newarr)

5
4
7
2
1
3
6
8
9
10


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Ans 3

In [4]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.ndim)
print(a.size)

2
9


# Ans 4

In [3]:
a_1d = np.array([18,19,15,16,14,13,12,11,17,1,2,3])
a_2d = a_1d[np.newaxis]
a2 = np.expand_dims(a_1d, axis=(1,-2,3))
a2.shape

print(a_1d)
print(a_1d.shape)
print()
print(a_2d)
print(a_2d.shape)

[18 19 15 16 14 13 12 11 17  1  2  3]
(12,)

[[18 19 15 16 14 13 12 11 17  1  2  3]]
(1, 12)


# Ans 5

In [13]:
v = np.array([[8,7],[4,3]])
h = np.array([[2,5],[3,7]])

print("Vertical Stack")
print(np.vstack((v,h)))

print("Horizontal Stack")
print(np.hstack((v,h)))

Vertical Stack
[[8 7]
 [4 3]
 [2 5]
 [3 7]]
Horizontal Stack
[[8 7 2 5]
 [4 3 3 7]]


# Ans 6

In [15]:
x = np.array([1,2,5,4,2,3,5,6,8,54,6,7,9,62,33,6,55,33,44,37,1,4])
unique, count = np.unique(x, return_counts = True)
print("Unique Items:",unique)
print("Unique Items Count:",count)

Unique Items: [ 1  2  3  4  5  6  7  8  9 33 37 44 54 55 62]
Unique Items Count: [2 2 1 2 2 3 1 1 1 2 1 1 1 1 1]
